{
 "kind": "discovery#restDescription",
 "etag": "\"FrPV2U6xXFUq8eRv_PO3IoAURkc/SUDnX6OXhxdKPeYmymDZoBwpT40\"",
 "discoveryVersion": "v1",
 "id": "genomics:v1beta",
 "name": "genomics",
 "version": "v1beta",
 "revision": "20140811",
 "title": "Genomics API",
 "description": "Provides access to Genomics data.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://developers.google.com/genomics/v1beta/reference",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/genomics/v1beta/",
 "basePath": "/genomics/v1beta/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "genomics/v1beta/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/bigquery": {
     "description": "View and manage your data in Google BigQuery"
    },
    "https://www.googleapis.com/auth/devstorage.read_write": {
     "description": "Manage your data in Google Cloud Storage"
    },
    "https://www.googleapis.com/auth/genomics": {
     "description": "View and manage Genomics data"
    },
    "https://www.googleapis.com/auth/genomics.readonly": {
     "description": "View Genomics data"
    }
   }
  }
 },
 "resources": {
  "beacons": {
   "methods": {
    "get": {
     "id": "genomics.beacons.get",
     "path": "beacons/{datasetId}",
     "httpMethod": "GET",
     "description": "This is an experimental API that provides a Global Alliance for Genomics and Health Beacon. It may change at any time."
    }
   }
  },
  "callsets": {
   "methods": {
    "create": {
     "id": "genomics.callsets.create",
     "path": "callsets",
     "httpMethod": "POST",
     "description": "Creates a new callset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.callsets.delete",
     "path": "callsets/{callsetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a callset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.callsets.get",
     "path": "callsets/{callsetId}",
     "httpMethod": "GET",
     "description": "Gets a callset by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.callsets.patch",
     "path": "callsets/{callsetId}",
     "httpMethod": "PATCH",
     "description": "Updates a callset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.callsets.search",
     "path": "callsets/search",
     "httpMethod": "POST",
     "description": "Gets a list of callsets matching the criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.callsets.update",
     "path": "callsets/{callsetId}",
     "httpMethod": "PUT",
     "description": "Updates a callset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "datasets": {
   "methods": {
    "create": {
     "id": "genomics.datasets.create",
     "path": "datasets",
     "httpMethod": "POST",
     "description": "Creates a new dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.datasets.delete",
     "path": "datasets/{datasetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.datasets.get",
     "path": "datasets/{datasetId}",
     "httpMethod": "GET",
     "description": "Gets a dataset by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "list": {
     "id": "genomics.datasets.list",
     "path": "datasets",
     "httpMethod": "GET",
     "description": "Lists all datasets.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "patch": {
     "id": "genomics.datasets.patch",
     "path": "datasets/{datasetId}",
     "httpMethod": "PATCH",
     "description": "Updates a dataset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "undelete": {
     "id": "genomics.datasets.undelete",
     "path": "datasets/{datasetId}/undelete",
     "httpMethod": "POST",
     "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. This operation is only possible for a week after the deletion occurred.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "update": {
     "id": "genomics.datasets.update",
     "path": "datasets/{datasetId}",
     "httpMethod": "PUT",
     "description": "Updates a dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  },
  "experimental": {
   "resources": {
    "jobs": {
     "methods": {
      "create": {
       "id": "genomics.experimental.jobs.create",
       "path": "experimental/jobs/create",
       "httpMethod": "POST",
       "description": "Creates and asynchronously runs an ad-hoc job. This is an experimental call and may be removed or changed at any time.",
       "scopes": [
        "https://www.googleapis.com/auth/devstorage.read_write",
        "https://www.googleapis.com/auth/genomics"
       ]
      }
     }
    }
   }
  },
  "jobs": {
   "methods": {
    "cancel": {
     "id": "genomics.jobs.cancel",
     "path": "jobs/{jobId}/cancel",
     "httpMethod": "POST",
     "description": "Cancels a job by ID. Note that it is possible for partial results to be generated and stored for cancelled jobs.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.jobs.get",
     "path": "jobs/{jobId}",
     "httpMethod": "GET",
     "description": "Gets a job by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "search": {
     "id": "genomics.jobs.search",
     "path": "jobs/search",
     "httpMethod": "POST",
     "description": "Gets a list of jobs matching the criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "reads": {
   "methods": {
    "search": {
     "id": "genomics.reads.search",
     "path": "reads/search",
     "httpMethod": "POST",
     "description": "Gets a list of reads for one or more readsets. Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested readsets are aligned. If a target positional range is specified, search returns all reads whose alignment to the reference genome overlap the range. A query which specifies only readset IDs yields all reads in those readsets, including unmapped reads. All reads returned (including rea[...]",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    }
   }
  },
  "readsets": {
   "methods": {
    "delete": {
     "id": "genomics.readsets.delete",
     "path": "readsets/{readsetId}",
     "httpMethod": "DELETE",
     "description": "Deletes a readset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.readsets.export",
     "path": "readsets/export",
     "httpMethod": "POST",
     "description": "Exports readsets to a BAM file in Google Cloud Storage. Note that currently there may be some differences between exported BAM files and the original BAM file at the time of import. In particular, comments in the input file header will not be preserved, and some custom tags will be converted to strings.",
     "scopes": [
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.readsets.get",
     "path": "readsets/{readsetId}",
     "httpMethod": "GET",
     "description": "Gets a readset by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "import": {
     "id": "genomics.readsets.import",
     "path": "readsets/import",
     "httpMethod": "POST",
     "description": "Creates readsets by asynchronously importing the provided information. Note that currently comments in the input file header are not imported and some custom tags will be converted to strings, rather than preserving tag types. The caller must have WRITE permissions to the dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.readsets.patch",
     "path": "readsets/{readsetId}",
     "httpMethod": "PATCH",
     "description": "Updates a readset. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.readsets.search",
     "path": "readsets/search",
     "httpMethod": "POST",
     "description": "Gets a list of readsets matching the criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.readsets.update",
     "path": "readsets/{readsetId}",
     "httpMethod": "PUT",
     "description": "Updates a readset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   },
   "resources": {
    "coveragebuckets": {
     "methods": {
      "list": {
       "id": "genomics.readsets.coveragebuckets.list",
       "path": "readsets/{readsetId}/coveragebuckets",
       "httpMethod": "GET",
       "description": "Lists fixed width coverage buckets for a readset, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range. Coverage is defined as the number of reads which are aligned to a given base in the reference sequence. Coverage buckets are available at various bucket widths, enabling various coverage \"zoom levels\". The caller must have READ permissions for the target readset.",
       "scopes": [
        "https://www.googleapis.com/auth/genomics",
        "https://www.googleapis.com/auth/genomics.readonly"
       ]
      }
     }
    }
   }
  },
  "variants": {
   "methods": {
    "create": {
     "id": "genomics.variants.create",
     "path": "variants",
     "httpMethod": "POST",
     "description": "Creates a new variant.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "delete": {
     "id": "genomics.variants.delete",
     "path": "variants/{variantId}",
     "httpMethod": "DELETE",
     "description": "Deletes a variant.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "export": {
     "id": "genomics.variants.export",
     "path": "variants/export",
     "httpMethod": "POST",
     "description": "Exports variant data to an external destination.",
     "scopes": [
      "https://www.googleapis.com/auth/bigquery",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "get": {
     "id": "genomics.variants.get",
     "path": "variants/{variantId}",
     "httpMethod": "GET",
     "description": "Gets a variant by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "getSummary": {
     "id": "genomics.variants.getSummary",
     "path": "variants/summary",
     "httpMethod": "GET",
     "description": "Gets a summary of all the variant data in a dataset.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "import": {
     "id": "genomics.variants.import",
     "path": "variants/import",
     "httpMethod": "POST",
     "description": "Creates variant data by asynchronously importing the provided information.",
     "scopes": [
      "https://www.googleapis.com/auth/devstorage.read_write",
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "patch": {
     "id": "genomics.variants.patch",
     "path": "variants/{variantId}",
     "httpMethod": "PATCH",
     "description": "Updates a variant. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    },
    "search": {
     "id": "genomics.variants.search",
     "path": "variants/search",
     "httpMethod": "POST",
     "description": "Gets a list of variants matching the criteria.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics",
      "https://www.googleapis.com/auth/genomics.readonly"
     ]
    },
    "update": {
     "id": "genomics.variants.update",
     "path": "variants/{variantId}",
     "httpMethod": "PUT",
     "description": "Updates a variant.",
     "scopes": [
      "https://www.googleapis.com/auth/genomics"
     ]
    }
   }
  }
 }
}
