include $(GOROOT)/src/Make.inc
PREREQ=$(QUOTED_GOROOT)/pkg/$(GOOS)_$(GOARCH)/google-api-go-client.googlecode.com/hg/google-api.a
TARG=google-api-go-client.googlecode.com/hg/blogger/v2
GOFILES=blogger-gen.go
include $(GOROOT)/src/Make.pkg
