{
 "kind": "discovery#restDescription",
 "discoveryVersion": "v1",
 "id": "youtube:v3alpha",
 "name": "youtube",
 "canonicalName": "YouTube",
 "version": "v3alpha",
 "revision": "20120827",
 "title": "YouTube API",
 "description": "Programmatic access to YouTube features.",
 "documentationLink": "https://developers.google.com/youtube",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/youtube/v3alpha/",
 "basePath": "/youtube/v3alpha/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/v3alpha/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.upload": {
     "description": "Manage your YouTube videos"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    }
   }
  }
 },
 "resources": {
  "channels": {
   "methods": {
    "list": {
     "id": "youtube.channels.list",
     "path": "channels",
     "httpMethod": "GET",
     "description": "Browse the YouTube channel collection. Either the 'id' or 'mine' parameter must be set.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "playlistItems": {
   "methods": {
    "list": {
     "id": "youtube.playlistItems.list",
     "path": "playlistItems",
     "httpMethod": "GET",
     "description": "Browse the YouTube playlist collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "playlists": {
   "methods": {
    "list": {
     "id": "youtube.playlists.list",
     "path": "playlists",
     "httpMethod": "GET",
     "description": "Browse the YouTube playlist collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "search": {
   "methods": {
    "list": {
     "id": "youtube.search.list",
     "path": "search",
     "httpMethod": "GET",
     "description": "Universal search for youtube.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "videos": {
   "methods": {
    "insert": {
     "id": "youtube.videos.insert",
     "path": "videos",
     "httpMethod": "POST",
     "description": "Upload a video to YouTube.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "youtube.videos.list",
     "path": "videos",
     "httpMethod": "GET",
     "description": "Browse the YouTube video collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  }
 }
}
