{
  "basePath": "",
  "documentationLink": "https://developers.google.com/people/",
  "id": "people:v1",
  "revision": "20170603",
  "discoveryVersion": "v1",
  "version_module": "True",
  "protocol": "rest",
  "canonicalName": "People Service",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/user.phonenumbers.read": {
          "description": "View your phone numbers"
        },
        "https://www.googleapis.com/auth/contacts.readonly": {
          "description": "View your contacts"
        },
        "https://www.googleapis.com/auth/user.birthday.read": {
          "description": "View your complete date of birth"
        },
        "https://www.googleapis.com/auth/plus.login": {
          "description": "Know the list of people in your circles, your age range, and language"
        },
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "View your basic profile info"
        },
        "https://www.googleapis.com/auth/user.emails.read": {
          "description": "View your email addresses"
        },
        "https://www.googleapis.com/auth/contacts": {
          "description": "Manage your contacts"
        },
        "https://www.googleapis.com/auth/user.addresses.read": {
          "description": "View your street addresses"
        }
      }
    }
  },
  "rootUrl": "https://people.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "people",
  "batchPath": "batch",
  "title": "Google People API",
  "ownerName": "Google",
  "resources": {
    "people": {
      "methods": {
        "getBatchGet": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people:batchGet",
          "id": "people.people.getBatchGet",
          "path": "v1/people:batchGet",
          "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser."
        },
        "get": {
          "description": "Provides information about a person by specifying a resource name. Use\n`people/me` to indicate the authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/plus.login",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "flatPath": "v1/people/{peopleId}",
          "id": "people.people.get",
          "path": "v1/{+resourceName}"
        }
      },
      "resources": {
        "connections": {
          "methods": {
            "list": {
              "description": "Provides a list of the authenticated user's contacts merged with any\nlinked profiles.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/contacts",
                "https://www.googleapis.com/auth/contacts.readonly"
              ],
              "flatPath": "v1/people/{peopleId}/connections",
              "path": "v1/{+resourceName}/connections",
              "id": "people.people.connections.list"
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://people.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Provides access to information about profiles and contacts.",
  "servicePath": ""
}
