include $(GOROOT)/src/Make.inc
PREREQ=$(QUOTED_GOROOT)/pkg/$(GOOS)_$(GOARCH)/google-api-go-client.googlecode.com/hg/google-api.a
TARG=google-api-go-client.googlecode.com/hg/taskqueue/v1beta1
GOFILES=taskqueue-gen.go
include $(GOROOT)/src/Make.pkg
