{
 "kind": "discovery#restDescription",
 "etag": "\"YWOzh2SDasdU84ArJnpYek-OMdg/jlUeQ39CT-heXQN-O7GqkbWfDjU\"",
 "discoveryVersion": "v1",
 "id": "supportcases:v2",
 "name": "supportcases",
 "version": "v2",
 "revision": "20170329",
 "title": "Google Support Cases Private API",
 "description": "Support Cases API",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://sites.google.com/a/google.com/cases/",
 "protocol": "rest",
 "baseUrl": "https://supportcases.googleapis.com/v2/",
 "basePath": "/v2/",
 "rootUrl": "https://supportcases.googleapis.com/",
 "servicePath": "v2/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cases": {
     "description": "View and manage your Google Support Cases"
    },
    "https://www.googleapis.com/auth/cases.readonly": {
     "description": "View your Google Support Cases"
    },
    "https://www.googleapis.com/auth/supportcontent": {
     "description": "View and manage your support data"
    }
   }
  }
 },
 "resources": {
  "agentActivities": {
   "methods": {
    "create": {
     "id": "supportcases.agentActivities.create",
     "path": "agentActivities",
     "httpMethod": "POST",
     "description": "Adds an agent activity.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createFromHelpCenterDeepLink": {
     "id": "supportcases.agentActivities.createFromHelpCenterDeepLink",
     "path": "agentActivities:createFromHelpCenterDeepLink",
     "httpMethod": "POST",
     "description": "Creates an agent activity from a help center deep link.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "list": {
     "id": "supportcases.agentActivities.list",
     "path": "agentActivities",
     "httpMethod": "GET",
     "description": "Lists an agent activities.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "agentSettings": {
   "methods": {
    "get": {
     "id": "supportcases.agentSettings.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets agent setting for the agent id in the resource name. If agent id is \"me\", get agent setting for the current logged in agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getPhoneSetting": {
     "id": "supportcases.agentSettings.getPhoneSetting",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets phone setting for the given agent id. If agent id is \"me\", gets phone setting for the agent currently logged in. This call is already deprecated.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getRealTimeSetting": {
     "id": "supportcases.agentSettings.getRealTimeSetting",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets agent's real time setting for the given agent id in the resource name. If agent id is \"me\", use the current logged in agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getSearchSetting": {
     "id": "supportcases.agentSettings.getSearchSetting",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets agent's search settings for the agent id in the resource name. If agent id is \"me\", use the current logged in agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "list": {
     "id": "supportcases.agentSettings.list",
     "path": "agentSettings",
     "httpMethod": "GET",
     "description": "List all agent settings.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listSettings": {
     "id": "supportcases.agentSettings.listSettings",
     "path": "{+name}:listSettings",
     "httpMethod": "GET",
     "description": "Lists settings for the agent id in the resource name. If agent id is \"me\", get agent setting for the current logged in agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "updateSearchSetting": {
     "id": "supportcases.agentSettings.updateSearchSetting",
     "path": "{+name}",
     "httpMethod": "PUT",
     "description": "Updates search settings for the agent id in the resource name. If agent id is \"me\", use the current logged in agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   }
  },
  "attributes": {
   "methods": {
    "get": {
     "id": "supportcases.attributes.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the specified attribute.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "cases": {
   "methods": {
    "assign": {
     "id": "supportcases.cases.assign",
     "path": "{+name}:assign",
     "httpMethod": "POST",
     "description": "Assigns the specified case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "autoAssign": {
     "id": "supportcases.cases.autoAssign",
     "path": "cases:autoAssign",
     "httpMethod": "POST",
     "description": "Auto assign a case to the calling user.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "block": {
     "id": "supportcases.cases.block",
     "path": "{+name}:block",
     "httpMethod": "POST",
     "description": "Indicate the specified case is blocked by a bug/case/legal order, etc.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "callBack": {
     "id": "supportcases.cases.callBack",
     "path": "{+name}:callBack",
     "httpMethod": "POST",
     "description": "Makes a callback. Deauthenticates customer.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createNewCase": {
     "id": "supportcases.cases.createNewCase",
     "path": "cases:createNewCase",
     "httpMethod": "POST",
     "description": "Creates a new case (Note this is not a true CRUD method as no resource is being passed in).",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createNoteConsult": {
     "id": "supportcases.cases.createNoteConsult",
     "path": "{+name}:createNoteConsult",
     "httpMethod": "POST",
     "description": "Creates a consult case via note channel for this case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createRealTimeConsult": {
     "id": "supportcases.cases.createRealTimeConsult",
     "path": "{+name}:createRealTimeConsult",
     "httpMethod": "POST",
     "description": "Creates a consult case via RealTime channel for this case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "dedupe": {
     "id": "supportcases.cases.dedupe",
     "path": "{+name}:dedupe",
     "httpMethod": "POST",
     "description": "Deduplicates a case by closing duplicates cases.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "escalate": {
     "id": "supportcases.cases.escalate",
     "path": "{+name}:escalate",
     "httpMethod": "POST",
     "description": "Escalates a case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "finish": {
     "id": "supportcases.cases.finish",
     "path": "{+name}:finish",
     "httpMethod": "POST",
     "description": "Sets the specified case to the finished state and triggers other finisher related workflows.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "get": {
     "id": "supportcases.cases.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the specified case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getAgentSearchCount": {
     "id": "supportcases.cases.getAgentSearchCount",
     "path": "cases:getAgentSearchCount",
     "httpMethod": "GET",
     "description": "Gets the search count for cases associated with the calling agent, and begin sending Tango notifications when the count changes.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getAgentUnreadCasesInfo": {
     "id": "supportcases.cases.getAgentUnreadCasesInfo",
     "path": "cases:GetAgentUnreadCasesInfo",
     "httpMethod": "GET",
     "description": "Gets information about unread cases for the calling agent. Only intended for use by the Cases frontend.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getConsultSla": {
     "id": "supportcases.cases.getConsultSla",
     "path": "{+name}:getConsultSla",
     "httpMethod": "POST",
     "description": "Calculates the SLA due by time that a new consult case would have.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listByAgent": {
     "id": "supportcases.cases.listByAgent",
     "path": "cases:listByAgent",
     "httpMethod": "GET",
     "description": "Lists cases associated with the agent. Only intended for use by the Cases frontend.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "needsInfo": {
     "id": "supportcases.cases.needsInfo",
     "path": "{+name}:needsInfo",
     "httpMethod": "POST",
     "description": "Sets the specified case to the needs info state.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "offeredSolution": {
     "id": "supportcases.cases.offeredSolution",
     "path": "{+name}:offeredSolution",
     "httpMethod": "POST",
     "description": "Sets the specified case to the solution offered state indicating that a previous communication was a \"solution\".",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "read": {
     "id": "supportcases.cases.read",
     "path": "{+name}:read",
     "httpMethod": "POST",
     "description": "Marks a case as read by the calling agent if they are the assignee.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "release": {
     "id": "supportcases.cases.release",
     "path": "{+name}:release",
     "httpMethod": "POST",
     "description": "Unassigns the specified case from the gaia user associated with this call.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "route": {
     "id": "supportcases.cases.route",
     "path": "{+name}:route",
     "httpMethod": "POST",
     "description": "Routes the specified case to another product or team.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "spam": {
     "id": "supportcases.cases.spam",
     "path": "{+name}:spam",
     "httpMethod": "POST",
     "description": "Marks the specified case as spam.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "split": {
     "id": "supportcases.cases.split",
     "path": "{+name}:split",
     "httpMethod": "POST",
     "description": "Move a case's communication into a new case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "suggestNewEmailHeaders": {
     "id": "supportcases.cases.suggestNewEmailHeaders",
     "path": "{+name}:suggestNewEmailHeaders",
     "httpMethod": "GET",
     "description": "Suggests a set of headers (like from aliases) for a new email on a case. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "suggestNoteHeaders": {
     "id": "supportcases.cases.suggestNoteHeaders",
     "path": "{+name}:suggestNoteHeaders",
     "httpMethod": "GET",
     "description": "Suggests a set of headers (like from aliases) for a note Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "take": {
     "id": "supportcases.cases.take",
     "path": "{+name}:take",
     "httpMethod": "POST",
     "description": "Assigns the specified case to the gaia user associated with this call.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "transfer": {
     "id": "supportcases.cases.transfer",
     "path": "{+name}:transfer",
     "httpMethod": "POST",
     "description": "Transfers the specified case from the gaia user associated with this call to another user.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "unassign": {
     "id": "supportcases.cases.unassign",
     "path": "{+name}:unassign",
     "httpMethod": "POST",
     "description": "Unassigns the specified case from its current assignee. Note that this also moves the case to the UNASSIGNED state.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "unblock": {
     "id": "supportcases.cases.unblock",
     "path": "{+name}:unblock",
     "httpMethod": "POST",
     "description": "Indicate the specified case is no longer blocked by a bug/case/ legal order, etc.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "unspam": {
     "id": "supportcases.cases.unspam",
     "path": "{+name}:unspam",
     "httpMethod": "POST",
     "description": "Unmark the specified case as spam.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "updateDisconnectedChannel": {
     "id": "supportcases.cases.updateDisconnectedChannel",
     "path": "{+name}:updateDisconnectedChannel",
     "httpMethod": "POST",
     "description": "Updates disconnected channel for the specified case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "updateEligibleProgram": {
     "id": "supportcases.cases.updateEligibleProgram",
     "path": "{+name}:updateEligibleProgram",
     "httpMethod": "POST",
     "description": "Update customer attributes indicating eligibility for opportunities.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "validateConsultForm": {
     "id": "supportcases.cases.validateConsultForm",
     "path": "cases:validateConsultForm",
     "httpMethod": "POST",
     "description": "Validates that consult forms are properly configured.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "waitForConsult": {
     "id": "supportcases.cases.waitForConsult",
     "path": "{+name}:WaitForConsult",
     "httpMethod": "POST",
     "description": "Sets a case with an active consult case to IN_CONSULT state.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   },
   "resources": {
    "attributes": {
     "methods": {
      "batchUpdate": {
       "id": "supportcases.cases.attributes.batchUpdate",
       "path": "{+name}:batchUpdate",
       "httpMethod": "POST",
       "description": "Updates attributes for a case in batch.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "update": {
       "id": "supportcases.cases.attributes.update",
       "path": "{+name}:update",
       "httpMethod": "POST",
       "description": "Updates attributes for the specified case. Note: This call adds the attributes that are not present on the case to the case. If attribute is already present on the case, the value is replaced.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    },
    "customer": {
     "methods": {
      "authenticate": {
       "id": "supportcases.cases.customer.authenticate",
       "path": "{+name}:authenticate",
       "httpMethod": "POST",
       "description": "Authenticates a customer for a case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "billingAddresses": {
       "id": "supportcases.cases.customer.billingAddresses",
       "path": "{+name}/customer/billingAddresses",
       "httpMethod": "POST",
       "description": "Lists customer billing addresses. Only intended for use by the Cases frontend.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "checkWalletAccount": {
       "id": "supportcases.cases.customer.checkWalletAccount",
       "path": "{+name}:checkWalletAccount",
       "httpMethod": "GET",
       "description": "Check if a customer has a valid Wallet account. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "deauthenticate": {
       "id": "supportcases.cases.customer.deauthenticate",
       "path": "{+name}:deauthenticate",
       "httpMethod": "POST",
       "description": "Deauthenticates a customer for a case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "getAuthenticationCreditCardTypes": {
       "id": "supportcases.cases.customer.getAuthenticationCreditCardTypes",
       "path": "{+name}:getAuthenticationCreditCardTypes",
       "httpMethod": "POST",
       "description": "Get credit card types for authentication.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getAuthenticationQuestions": {
       "id": "supportcases.cases.customer.getAuthenticationQuestions",
       "path": "{+name}:getAuthenticationQuestions",
       "httpMethod": "POST",
       "description": "Get authentication options for a customer for a case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getAuthenticationResult": {
       "id": "supportcases.cases.customer.getAuthenticationResult",
       "path": "{+name}:getAuthenticationResult",
       "httpMethod": "POST",
       "description": "Get authentication status for a customer of a case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "getBusinessListings": {
       "id": "supportcases.cases.customer.getBusinessListings",
       "path": "{+name}:getBusinessListings",
       "httpMethod": "POST",
       "description": "Gets the business listings for a customer.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "shippingAddresses": {
       "id": "supportcases.cases.customer.shippingAddresses",
       "path": "{+name}/customer/shippingAddresses",
       "httpMethod": "POST",
       "description": "Lists customer shipping addresses. Only intended for use by the Cases frontend.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "updateContactEmail": {
       "id": "supportcases.cases.customer.updateContactEmail",
       "path": "{+name}:updateContactEmail",
       "httpMethod": "POST",
       "description": "Updates contact email for the specified case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "updateContactName": {
       "id": "supportcases.cases.customer.updateContactName",
       "path": "{+name}:updateContactName",
       "httpMethod": "POST",
       "description": "Updates contact name for the specified case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "updateCustomerAttributes": {
       "id": "supportcases.cases.customer.updateCustomerAttributes",
       "path": "{+name}:updateCustomerAttributes",
       "httpMethod": "POST",
       "description": "Updates customer attributes for the specified case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     },
     "resources": {
      "contact": {
       "methods": {
        "callbackNumber": {
         "id": "supportcases.cases.customer.contact.callbackNumber",
         "path": "{+name}",
         "httpMethod": "POST",
         "description": "Sets a callback phone number.",
         "scopes": [
          "https://www.googleapis.com/auth/cases"
         ]
        },
        "getCallbackNumber": {
         "id": "supportcases.cases.customer.contact.getCallbackNumber",
         "path": "{+name}",
         "httpMethod": "GET",
         "description": "Gets the callback phone number associated with a case.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        }
       }
      }
     }
    },
    "issue": {
     "methods": {
      "updateAccounts": {
       "id": "supportcases.cases.issue.updateAccounts",
       "path": "{+name}",
       "httpMethod": "PUT",
       "description": "Updates case's accounts.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "updateLocale": {
       "id": "supportcases.cases.issue.updateLocale",
       "path": "{+name}:updateLocale",
       "httpMethod": "POST",
       "description": "Updates the case's issue locale.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "updateProduct": {
       "id": "supportcases.cases.issue.updateProduct",
       "path": "{+name}",
       "httpMethod": "PUT",
       "description": "Updates product for the specified case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "updateSummary": {
       "id": "supportcases.cases.issue.updateSummary",
       "path": "{+name}:updateSummary",
       "httpMethod": "POST",
       "description": "Updates case's issue summary.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     },
     "resources": {
      "product": {
       "methods": {
        "updateAgentCategories": {
         "id": "supportcases.cases.issue.product.updateAgentCategories",
         "path": "{+name}:updateAgentCategories",
         "httpMethod": "POST",
         "description": "Updates agent categories for the specified case. Note: This call replaces categories on the case by new categories passed in the request.",
         "scopes": [
          "https://www.googleapis.com/auth/cases"
         ]
        }
       }
      }
     }
    },
    "workflows": {
     "methods": {
      "get": {
       "id": "supportcases.cases.workflows.get",
       "path": "{+name}",
       "httpMethod": "GET",
       "description": "Get workflow state.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "post": {
       "id": "supportcases.cases.workflows.post",
       "path": "{+name}",
       "httpMethod": "POST",
       "description": "Creates a new workflow state on a case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "update": {
       "id": "supportcases.cases.workflows.update",
       "path": "{+name}:update",
       "httpMethod": "PUT",
       "description": "Updates workflow state.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    }
   }
  },
  "categoryInfos": {
   "methods": {
    "batchGet": {
     "id": "supportcases.categoryInfos.batchGet",
     "path": "categoryInfos:batchGet",
     "httpMethod": "GET",
     "description": "Batch gets category info. (Best effort, returns valid category infos only) Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "get": {
     "id": "supportcases.categoryInfos.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the specified category info.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listChildren": {
     "id": "supportcases.categoryInfos.listChildren",
     "path": "{+name}:listChildren",
     "httpMethod": "GET",
     "description": "Lists children category info.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listTopLevel": {
     "id": "supportcases.categoryInfos.listTopLevel",
     "path": "categoryInfos:listTopLevel",
     "httpMethod": "GET",
     "description": "Lists gKMS top level category info.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "search": {
     "id": "supportcases.categoryInfos.search",
     "path": "categoryInfos:search",
     "httpMethod": "GET",
     "description": "Searches category info. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "searchMultiple": {
     "id": "supportcases.categoryInfos.searchMultiple",
     "path": "categoryInfos:searchMultiple",
     "httpMethod": "POST",
     "description": "Searches multiple category info.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   },
   "resources": {
    "properties": {
     "methods": {
      "list": {
       "id": "supportcases.categoryInfos.properties.list",
       "path": "{+name}/properties",
       "httpMethod": "GET",
       "description": "Lists all properties associated with a category info.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    }
   }
  },
  "communications": {
   "methods": {
    "buildNewEmail": {
     "id": "supportcases.communications.buildNewEmail",
     "path": "communications:buildNewEmail",
     "httpMethod": "POST",
     "description": "Builds an email template for the first email on a case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "buildReplyEmail": {
     "id": "supportcases.communications.buildReplyEmail",
     "path": "communications:buildReplyEmail",
     "httpMethod": "POST",
     "description": "Builds an email template for a reply to an existing email.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "cancelSend": {
     "id": "supportcases.communications.cancelSend",
     "path": "{+name}:cancelSend",
     "httpMethod": "POST",
     "description": "Cancel a pending send (for email only).",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createConsultNote": {
     "id": "supportcases.communications.createConsultNote",
     "path": "communications:createConsultNote",
     "httpMethod": "POST",
     "description": "Creates a draft note that replies to a consult note.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createEmail": {
     "id": "supportcases.communications.createEmail",
     "path": "communications:createEmail",
     "httpMethod": "POST",
     "description": "Creates a draft email and adds it to a case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createNote": {
     "id": "supportcases.communications.createNote",
     "path": "communications:createNote",
     "httpMethod": "POST",
     "description": "Creates a note.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "discardDraft": {
     "id": "supportcases.communications.discardDraft",
     "path": "{+name}:discardDraft",
     "httpMethod": "POST",
     "description": "Discards a draft communication.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "finalizeConsultNote": {
     "id": "supportcases.communications.finalizeConsultNote",
     "path": "{+name}:finalizeConsultNote",
     "httpMethod": "POST",
     "description": "Finalizes and sends a draft note for a consult case.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "finalizeNote": {
     "id": "supportcases.communications.finalizeNote",
     "path": "{+name}:finalizeNote",
     "httpMethod": "POST",
     "description": "Finalize a note (a note cannot be updated after it is finalized).",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "list": {
     "id": "supportcases.communications.list",
     "path": "communications",
     "httpMethod": "GET",
     "description": "Lists communications that match the filter.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listRelated": {
     "id": "supportcases.communications.listRelated",
     "path": "communications:listRelated",
     "httpMethod": "GET",
     "description": "Lists communications that are related to each other, including the communications on the requested case. Related communications include consult communications from target cases. Currently, only related communications from consult cases are supported.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "send": {
     "id": "supportcases.communications.send",
     "path": "{+name}:send",
     "httpMethod": "POST",
     "description": "Sends a draft email. This finalizes the email.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "suggestReplyEmailHeaders": {
     "id": "supportcases.communications.suggestReplyEmailHeaders",
     "path": "communications:suggestReplyEmailHeaders",
     "httpMethod": "GET",
     "description": "Suggests a set of email headers for an email reply to another email. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "updateConsultNote": {
     "id": "supportcases.communications.updateConsultNote",
     "path": "{+name}:updateConsultNote",
     "httpMethod": "POST",
     "description": "Updates a draft consult note with new content.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "updateEmail": {
     "id": "supportcases.communications.updateEmail",
     "path": "{+name}:updateEmail",
     "httpMethod": "POST",
     "description": "Updates a draft email.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "updateNote": {
     "id": "supportcases.communications.updateNote",
     "path": "{+name}:updateNote",
     "httpMethod": "POST",
     "description": "Updates a draft note.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   },
   "resources": {
    "attachments": {
     "methods": {
      "delete": {
       "id": "supportcases.communications.attachments.delete",
       "path": "{+name}",
       "httpMethod": "DELETE",
       "description": "Deletes an attachment from a draft.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    }
   }
  },
  "customerInteractions": {
   "methods": {
    "list": {
     "id": "supportcases.customerInteractions.list",
     "path": "customerInteractions",
     "httpMethod": "GET",
     "description": "List customer interactions.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "summarize": {
     "id": "supportcases.customerInteractions.summarize",
     "path": "customerInteractions:summarize",
     "httpMethod": "GET",
     "description": "Summary statistics about the cutomer's interaction history. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "customerIssues": {
   "methods": {
    "list": {
     "id": "supportcases.customerIssues.list",
     "path": "customerIssues:list",
     "httpMethod": "GET",
     "description": "List issues and their resolutions for a customer.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "devices": {
   "methods": {
    "getById": {
     "id": "supportcases.devices.getById",
     "path": "devices:getById",
     "httpMethod": "GET",
     "description": "Gets the specified device by any device ID.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "list": {
     "id": "supportcases.devices.list",
     "path": "devices",
     "httpMethod": "GET",
     "description": "List devices.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "updateOwner": {
     "id": "supportcases.devices.updateOwner",
     "path": "devices:updateOwner",
     "httpMethod": "GET",
     "description": "Updates the owner of a device. Suppresses warning: GET requires method name starting with \"Get\" or \"List\"",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   }
  },
  "giftCards": {
   "methods": {
    "checkRedeemer": {
     "id": "supportcases.giftCards.checkRedeemer",
     "path": "giftCards:checkRedeemer",
     "httpMethod": "POST",
     "description": "If the card is already redeemed by somebody else, customer can try a few users.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "lookup": {
     "id": "supportcases.giftCards.lookup",
     "path": "giftCards:lookup",
     "httpMethod": "POST",
     "description": "Finds a gift card based on its full redemption code or activation number. With full redemption code, returns redemption token on success.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "redeem": {
     "id": "supportcases.giftCards.redeem",
     "path": "giftCards:redeem",
     "httpMethod": "POST",
     "description": "Redeems a gift card to a customer using the redemption token.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "verify": {
     "id": "supportcases.giftCards.verify",
     "path": "giftCards:verify",
     "httpMethod": "POST",
     "description": "Verifies ownership of a damaged GC by checking if the activation number and partial redemption code are valid and refers to the same card. Returns the redemption token on success.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "ginlogs": {
   "methods": {
    "logDataAccess": {
     "id": "supportcases.ginlogs.logDataAccess",
     "path": "ginlogs:logDataAccess",
     "httpMethod": "POST",
     "description": "Logs data access.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   }
  },
  "hardwareAuditor": {
   "resources": {
    "orders": {
     "methods": {
      "cancel": {
       "id": "supportcases.hardwareAuditor.orders.cancel",
       "path": "{+name}:cancel",
       "httpMethod": "POST",
       "description": "Cancels the hardware order.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "getDetail": {
       "id": "supportcases.hardwareAuditor.orders.getDetail",
       "path": "{+name}:getDetail",
       "httpMethod": "POST",
       "description": "Gets detail for a hardware order.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getShippingAddress": {
       "id": "supportcases.hardwareAuditor.orders.getShippingAddress",
       "path": "{+name}:getShippingAddress",
       "httpMethod": "POST",
       "description": "Gets shipping address for a purchase. Get by orderId: /v2/hardwareAuditor/orders/ DEPRECATED TODO(b/34705382)",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getShippingCustomerName": {
       "id": "supportcases.hardwareAuditor.orders.getShippingCustomerName",
       "path": "{+name}:getShippingCustomerName",
       "httpMethod": "POST",
       "description": "Gets the shipping customer name for a hardware order Get by orderId: /v2/hardwareAuditor/orders/ DEPRECATED TODO(b/34705382)",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getShippingCustomerPhoneNumber": {
       "id": "supportcases.hardwareAuditor.orders.getShippingCustomerPhoneNumber",
       "path": "{+name}:getShippingCustomerPhoneNumber",
       "httpMethod": "POST",
       "description": "Gets the shipping customer phone number for a hardware order Get by orderId: /v2/hardwareAuditor/orders/ DEPRECATED TODO(b/34705382)",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "list": {
       "id": "supportcases.hardwareAuditor.orders.list",
       "path": "hardwareAuditor/orders:list",
       "httpMethod": "POST",
       "description": "Lists hardware orders.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "refunds": {
       "id": "supportcases.hardwareAuditor.orders.refunds",
       "path": "{+name}/refunds",
       "httpMethod": "POST",
       "description": "Lists refunds for a hardware order.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    },
    "shipments": {
     "methods": {
      "cancel": {
       "id": "supportcases.hardwareAuditor.shipments.cancel",
       "path": "{+name}:cancel",
       "httpMethod": "POST",
       "description": "Cancels the hardware order by shipment id.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      },
      "getShippingAddress": {
       "id": "supportcases.hardwareAuditor.shipments.getShippingAddress",
       "path": "{+name}:getShippingAddress",
       "httpMethod": "POST",
       "description": "--------- Begin of shipment Id based calls ----------------- Gets shipping address for a purchase Get by shipmentId: /v2/hardwareAuditor/shipments/:",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getShippingCustomerName": {
       "id": "supportcases.hardwareAuditor.shipments.getShippingCustomerName",
       "path": "{+name}:getShippingCustomerName",
       "httpMethod": "POST",
       "description": "Gets the shipping customer name for a hardware order Get by shipmentId: /v2/hardwareAuditor/shipments/:",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getShippingCustomerPhoneNumber": {
       "id": "supportcases.hardwareAuditor.shipments.getShippingCustomerPhoneNumber",
       "path": "{+name}:getShippingCustomerPhoneNumber",
       "httpMethod": "POST",
       "description": "Gets the shipping customer phone number for a hardware order Get by shipmentId: /v2/hardwareAuditor/shipments/:",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "refunds": {
       "id": "supportcases.hardwareAuditor.shipments.refunds",
       "path": "{+name}/refunds",
       "httpMethod": "POST",
       "description": "Lists refunds for a hardware order. Get by shipmentId: /v2/hardwareAuditor/shipments/:",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    }
   }
  },
  "hardwareOrders": {
   "methods": {
    "cancel": {
     "id": "supportcases.hardwareOrders.cancel",
     "path": "{+name}:cancel",
     "httpMethod": "POST",
     "description": "Cancels the hardware order.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "getDetail": {
     "id": "supportcases.hardwareOrders.getDetail",
     "path": "{+name}:getDetail",
     "httpMethod": "POST",
     "description": "Gets detail for a hardware order.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getLostStolenRefundEligibility": {
     "id": "supportcases.hardwareOrders.getLostStolenRefundEligibility",
     "path": "{+name}:getLostStolenRefundEligibility",
     "httpMethod": "POST",
     "description": "Gets lost stolen refund eligibility for account Get by orderId: /v2/hardwareOrders/ DEPRECATED TODO(b/34705382)",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingAddress": {
     "id": "supportcases.hardwareOrders.getShippingAddress",
     "path": "{+name}:getShippingAddress",
     "httpMethod": "POST",
     "description": "Gets shipping address for a purchase Get by orderId: /v2/hardwareOrders/ DEPRECATED TODO(b/34705382)",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingCustomerName": {
     "id": "supportcases.hardwareOrders.getShippingCustomerName",
     "path": "{+name}:getShippingCustomerName",
     "httpMethod": "POST",
     "description": "Gets the shipping customer name for a hardware order Get by orderId: /v2/hardwareOrders/ DEPRECATED TODO(b/34705382)",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingCustomerPhoneNumber": {
     "id": "supportcases.hardwareOrders.getShippingCustomerPhoneNumber",
     "path": "{+name}:getShippingCustomerPhoneNumber",
     "httpMethod": "POST",
     "description": "Gets the shipping customer phone number for a hardware order Get by orderId: /v2/hardwareOrders/ DEPRECATED TODO(b/34705382)",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "hardwareSignals": {
     "id": "supportcases.hardwareOrders.hardwareSignals",
     "path": "hardwareOrders:hardwareSignals",
     "httpMethod": "POST",
     "description": "Gets hardware signals based on the case and customer.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "list": {
     "id": "supportcases.hardwareOrders.list",
     "path": "hardwareOrders:list",
     "httpMethod": "POST",
     "description": "Lists hardware orders.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listOtherDevices": {
     "id": "supportcases.hardwareOrders.listOtherDevices",
     "path": "hardwareOrders:listOtherDevices",
     "httpMethod": "POST",
     "description": "Gets a user's devices that are not in the ListHardwareOrders result.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "refund": {
     "id": "supportcases.hardwareOrders.refund",
     "path": "{+name}:refund",
     "httpMethod": "POST",
     "description": "Refunds a hardware order",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "refunds": {
     "id": "supportcases.hardwareOrders.refunds",
     "path": "{+name}/refunds",
     "httpMethod": "POST",
     "description": "Lists refunds for a hardware order. Get by orderId: /v2/hardwareOrders/ DEPRECATED TODO(b/34705382)",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "hardwareShipments": {
   "methods": {
    "cancel": {
     "id": "supportcases.hardwareShipments.cancel",
     "path": "{+name}:cancel",
     "httpMethod": "POST",
     "description": "Cancels the hardware shipment by shipment id.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "getLostStolenRefundEligibility": {
     "id": "supportcases.hardwareShipments.getLostStolenRefundEligibility",
     "path": "{+name}:getLostStolenRefundEligibility",
     "httpMethod": "POST",
     "description": "Gets lost stolen refund eligibility for account Get by shipmentId: /v2/hardwareShipments/:",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingAddress": {
     "id": "supportcases.hardwareShipments.getShippingAddress",
     "path": "{+name}:getShippingAddress",
     "httpMethod": "POST",
     "description": "--------- Begin of shipment Id based calls ----------------- Gets shipping address for a purchase Get by shipmentId: /v2/hardwareShipments/:",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingCustomerName": {
     "id": "supportcases.hardwareShipments.getShippingCustomerName",
     "path": "{+name}:getShippingCustomerName",
     "httpMethod": "POST",
     "description": "Gets the shipping customer name for a hardware order Get by shipmentId: /v2/hardwareShipments/:",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getShippingCustomerPhoneNumber": {
     "id": "supportcases.hardwareShipments.getShippingCustomerPhoneNumber",
     "path": "{+name}:getShippingCustomerPhoneNumber",
     "httpMethod": "POST",
     "description": "Gets the shipping customer phone number for a hardware order Get by shipmentId: /v2/hardwareShipments/:",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "refund": {
     "id": "supportcases.hardwareShipments.refund",
     "path": "{+name}:refund",
     "httpMethod": "POST",
     "description": "Refunds a hardware shipment by shipment id.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "refunds": {
     "id": "supportcases.hardwareShipments.refunds",
     "path": "{+name}/refunds",
     "httpMethod": "POST",
     "description": "Lists refunds for a hardware order. Get by shipmentId: /v2/hardwareShipments/:",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "opportunities": {
   "methods": {
    "list": {
     "id": "supportcases.opportunities.list",
     "path": "opportunities",
     "httpMethod": "GET",
     "description": "Lists opportunities.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   },
   "resources": {
    "pitches": {
     "methods": {
      "batchCreate": {
       "id": "supportcases.opportunities.pitches.batchCreate",
       "path": "opportunities/pitches:batchCreate",
       "httpMethod": "POST",
       "description": "Batch creates pitches.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    }
   }
  },
  "play": {
   "resources": {
    "digitalContent": {
     "methods": {
      "getRefundStatus": {
       "id": "supportcases.play.digitalContent.getRefundStatus",
       "path": "play/digitalContent:getRefundStatus",
       "httpMethod": "POST",
       "description": "Get refund status.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     },
     "resources": {
      "orders": {
       "methods": {
        "batchGet": {
         "id": "supportcases.play.digitalContent.orders.batchGet",
         "path": "play/digitalContent/orders:batchGet",
         "httpMethod": "POST",
         "description": "Get a collection of orders.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        },
        "refund": {
         "id": "supportcases.play.digitalContent.orders.refund",
         "path": "play/digitalContent/orders:refund",
         "httpMethod": "POST",
         "description": "Refund orders.",
         "scopes": [
          "https://www.googleapis.com/auth/cases"
         ]
        },
        "search": {
         "id": "supportcases.play.digitalContent.orders.search",
         "path": "play/digitalContent/orders:search",
         "httpMethod": "POST",
         "description": "Search for orders.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        }
       }
      },
      "subscriptions": {
       "methods": {
        "batchGet": {
         "id": "supportcases.play.digitalContent.subscriptions.batchGet",
         "path": "play/digitalContent/subscriptions:batchGet",
         "httpMethod": "POST",
         "description": "Get a collection of subscriptions.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        },
        "cancel": {
         "id": "supportcases.play.digitalContent.subscriptions.cancel",
         "path": "play/digitalContent/subscriptions:cancel",
         "httpMethod": "POST",
         "description": "Cancel subscription.",
         "scopes": [
          "https://www.googleapis.com/auth/cases"
         ]
        },
        "getCancellationStatus": {
         "id": "supportcases.play.digitalContent.subscriptions.getCancellationStatus",
         "path": "play/digitalContent/subscriptions:getCancellationStatus",
         "httpMethod": "POST",
         "description": "Get cancellation status.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        },
        "list": {
         "id": "supportcases.play.digitalContent.subscriptions.list",
         "path": "play/digitalContent/subscriptions:list",
         "httpMethod": "POST",
         "description": "List subscriptions.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        }
       }
      }
     }
    }
   }
  },
  "products": {
   "methods": {
    "get": {
     "id": "supportcases.products.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the specified product.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getEscalationTargets": {
     "id": "supportcases.products.getEscalationTargets",
     "path": "{+name}:getEscalationTargets",
     "httpMethod": "GET",
     "description": "Gets the available escalation targets.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getRoutingTargets": {
     "id": "supportcases.products.getRoutingTargets",
     "path": "{+name}:getRoutingTargets",
     "httpMethod": "GET",
     "description": "Gets the available routing targets.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getSettings": {
     "id": "supportcases.products.getSettings",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the settings for a specified product.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "list": {
     "id": "supportcases.products.list",
     "path": "products",
     "httpMethod": "GET",
     "description": "Lists products.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listSettings": {
     "id": "supportcases.products.listSettings",
     "path": "{+name}:listSettings",
     "httpMethod": "GET",
     "description": "Lists product settings for an agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "resolutions": {
   "methods": {
    "list": {
     "id": "supportcases.resolutions.list",
     "path": "resolutions",
     "httpMethod": "GET",
     "description": "Query for resolutions.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "log": {
     "id": "supportcases.resolutions.log",
     "path": "resolutions:log",
     "httpMethod": "POST",
     "description": "Log a resolution.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "suggest": {
     "id": "supportcases.resolutions.suggest",
     "path": "resolutions:suggest",
     "httpMethod": "POST",
     "description": "Suggest some resolutions to a case based on provided signals.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    }
   },
   "resources": {
    "cohorts": {
     "methods": {
      "assign": {
       "id": "supportcases.resolutions.cohorts.assign",
       "path": "resolutions/cohorts:assign",
       "httpMethod": "POST",
       "description": "Query and assign cohorts for this case.",
       "scopes": [
        "https://www.googleapis.com/auth/cases",
        "https://www.googleapis.com/auth/supportcontent"
       ]
      }
     }
    }
   }
  },
  "rma": {
   "methods": {
    "save": {
     "id": "supportcases.rma.save",
     "path": "rma:save",
     "httpMethod": "POST",
     "description": "Saves (Insert/Update) an RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "submit": {
     "id": "supportcases.rma.submit",
     "path": "rma:submit",
     "httpMethod": "POST",
     "description": "DEPRECATED: Use SendRma instead. Submit an RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   }
  },
  "rmas": {
   "methods": {
    "cancel": {
     "id": "supportcases.rmas.cancel",
     "path": "{+name}:cancel",
     "httpMethod": "POST",
     "description": "Cancel an RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "cancelAuthHold": {
     "id": "supportcases.rmas.cancelAuthHold",
     "path": "{+name}:cancelAuthHold",
     "httpMethod": "POST",
     "description": "Cancels an auth hold for an advanced exchange RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "createExchangeWithoutReturn": {
     "id": "supportcases.rmas.createExchangeWithoutReturn",
     "path": "rmas:createExchangeWithoutReturn",
     "httpMethod": "POST",
     "description": "Sends merchandise without expecting a return.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "get": {
     "id": "supportcases.rmas.get",
     "path": "{+name}",
     "httpMethod": "GET",
     "description": "Gets the specified RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getLostStolenEligibility": {
     "id": "supportcases.rmas.getLostStolenEligibility",
     "path": "{+name}:getLostStolenEligibility",
     "httpMethod": "POST",
     "description": "Determines the eligibility of a lost/stolen RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getMailingAddress": {
     "id": "supportcases.rmas.getMailingAddress",
     "path": "{+name}:getMailingAddress",
     "httpMethod": "POST",
     "description": "Get mailing address for an RMA",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getOrderDetail": {
     "id": "supportcases.rmas.getOrderDetail",
     "path": "{+name}:getOrderDetail",
     "httpMethod": "POST",
     "description": "Gets an RMA's order detail.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "getReplacementDetail": {
     "id": "supportcases.rmas.getReplacementDetail",
     "path": "{+name}:getReplacementDetail",
     "httpMethod": "POST",
     "description": "Get details for a replacement device that is not associated with an order.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "list": {
     "id": "supportcases.rmas.list",
     "path": "rmas",
     "httpMethod": "GET",
     "description": "Lists RMAs by Case ID and RMA state",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "listBuyersRemorseCountryCodes": {
     "id": "supportcases.rmas.listBuyersRemorseCountryCodes",
     "path": "rmas:listBuyersRemorseCountryCodes",
     "httpMethod": "GET",
     "description": "Lists two-character country codes valid for Buyer's Remorse RMAs.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "markOriginalDeviceReceived": {
     "id": "supportcases.rmas.markOriginalDeviceReceived",
     "path": "{+name}:markOriginalDeviceReceived",
     "httpMethod": "POST",
     "description": "Marks an original device as received in a Standard Exchange.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "runRmaSteps": {
     "id": "supportcases.rmas.runRmaSteps",
     "path": "{+name}:runRmaSteps",
     "httpMethod": "POST",
     "description": "Run the given RMA workflow steps.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "runWorkflow": {
     "id": "supportcases.rmas.runWorkflow",
     "path": "rmas:runWorkflow",
     "httpMethod": "POST",
     "description": "DEPRECATED: Use RunRmaSteps instead. Run the given workflow for an RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    },
    "send": {
     "id": "supportcases.rmas.send",
     "path": "rmas:send",
     "httpMethod": "POST",
     "description": "Initiates a new RMA.",
     "scopes": [
      "https://www.googleapis.com/auth/cases"
     ]
    }
   }
  },
  "teams": {
   "methods": {
    "getMyAssignStreamSearches": {
     "id": "supportcases.teams.getMyAssignStreamSearches",
     "path": "teams:getMyAssignStreamSearches",
     "httpMethod": "GET",
     "description": "Gets assign-stream-enabled searches associated with the agent.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   }
  },
  "troubleshooterSessions": {
   "methods": {
    "create": {
     "id": "supportcases.troubleshooterSessions.create",
     "path": "troubleshooterSessions:create",
     "httpMethod": "POST",
     "description": "Start a new troubleshooter session.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "listDevices": {
     "id": "supportcases.troubleshooterSessions.listDevices",
     "path": "troubleshooterSessions:listDevices",
     "httpMethod": "POST",
     "description": "Lists devices on a customer's account.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "listIssues": {
     "id": "supportcases.troubleshooterSessions.listIssues",
     "path": "troubleshooterSessions:listIssues",
     "httpMethod": "GET",
     "description": "Lists issues.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "listPurchasedApps": {
     "id": "supportcases.troubleshooterSessions.listPurchasedApps",
     "path": "troubleshooterSessions:listPurchasedApps",
     "httpMethod": "POST",
     "description": "Lists purchased apps on a customer's account.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "listPurchasedBooks": {
     "id": "supportcases.troubleshooterSessions.listPurchasedBooks",
     "path": "troubleshooterSessions:listPurchasedBooks",
     "httpMethod": "POST",
     "description": "Lists purchased books on a customer's account.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "listPurchasedVideos": {
     "id": "supportcases.troubleshooterSessions.listPurchasedVideos",
     "path": "troubleshooterSessions:listPurchasedVideos",
     "httpMethod": "POST",
     "description": "Lists purchased videos on a customer's account.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "log": {
     "id": "supportcases.troubleshooterSessions.log",
     "path": "{+name}:log",
     "httpMethod": "POST",
     "description": "Log troubleshooter activity.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    },
    "troubleshootIssue": {
     "id": "supportcases.troubleshooterSessions.troubleshootIssue",
     "path": "{+name}:troubleshootIssue",
     "httpMethod": "POST",
     "description": "Troubleshoot issue.",
     "scopes": [
      "https://www.googleapis.com/auth/cases",
      "https://www.googleapis.com/auth/supportcontent"
     ]
    }
   }
  },
  "wallets": {
   "methods": {
    "bankAccountCountries": {
     "id": "supportcases.wallets.bankAccountCountries",
     "path": "wallets/bankAccountCountries",
     "httpMethod": "POST",
     "description": "List supported Bank Account countries. Initially will only return supported Bank Account countries for Payment Method Hijacks (PMH). This is a POST API because it takes in a sso_ticket.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "creditCardTypes": {
     "id": "supportcases.wallets.creditCardTypes",
     "path": "wallets/creditCardTypes",
     "httpMethod": "POST",
     "description": "List supported Credit Card types. Initially will only return supported credit cards for Payment Method Hijacks (PMH). This is a POST API because it takes in a sso_ticket.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "transactions": {
     "id": "supportcases.wallets.transactions",
     "path": "wallets/transactions",
     "httpMethod": "POST",
     "description": "Query for transactions.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "troubleshootAccount": {
     "id": "supportcases.wallets.troubleshootAccount",
     "path": "wallets:troubleshootAccount",
     "httpMethod": "POST",
     "description": "Troubleshoots a Wallet account for issues.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "troubleshootTransaction": {
     "id": "supportcases.wallets.troubleshootTransaction",
     "path": "wallets:troubleshootTransaction",
     "httpMethod": "POST",
     "description": "Troubleshoots a Wallet transaction for issues.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   },
   "resources": {
    "accounts": {
     "methods": {
      "getPaymentsInfo": {
       "id": "supportcases.wallets.accounts.getPaymentsInfo",
       "path": "wallets/accounts:getPaymentsInfo",
       "httpMethod": "POST",
       "description": "Fetches Payments info, such as number of Payments accounts for the user.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getReviewStatus": {
       "id": "supportcases.wallets.accounts.getReviewStatus",
       "path": "wallets/accounts:getReviewStatus",
       "httpMethod": "POST",
       "description": "Fetches the review status of a wallet account. This is a POST API because it takes in a sso_ticket.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "getSignals": {
       "id": "supportcases.wallets.accounts.getSignals",
       "path": "wallets/accounts:getSignals",
       "httpMethod": "GET",
       "description": "Fetches Wallet account signals for troubleshooting Wallet issues.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "searchReviews": {
       "id": "supportcases.wallets.accounts.searchReviews",
       "path": "wallets/accounts:searchReviews",
       "httpMethod": "POST",
       "description": "Initiates a review on the Wallet account. This is a POST API because it takes in a sso_ticket. This API could lead to a review escalation (increase in priority).",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     },
     "resources": {
      "paymentInstruments": {
       "methods": {
        "getHijackReviewsStatus": {
         "id": "supportcases.wallets.accounts.paymentInstruments.getHijackReviewsStatus",
         "path": "wallets/accounts/paymentInstruments:getHijackReviewsStatus",
         "httpMethod": "POST",
         "description": "Retrieve status for Payment Method Hijack (PMH) reviews. This is a POST API because it takes in a sso_ticket.",
         "scopes": [
          "https://www.googleapis.com/auth/cases.readonly"
         ]
        },
        "initiateHijackReviews": {
         "id": "supportcases.wallets.accounts.paymentInstruments.initiateHijackReviews",
         "path": "wallets/accounts/paymentInstruments:initiateHijackReviews",
         "httpMethod": "POST",
         "description": "Initiate Payment Method Hijack (PMH) reviews.",
         "scopes": [
          "https://www.googleapis.com/auth/cases"
         ]
        }
       }
      }
     }
    },
    "paymentInstrumentTypeInfos": {
     "methods": {
      "list": {
       "id": "supportcases.wallets.paymentInstrumentTypeInfos.list",
       "path": "wallets/paymentInstrumentTypeInfos",
       "httpMethod": "GET",
       "description": "List supported payment instrument types. This API is not customer contextual.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    },
    "paymentInstruments": {
     "methods": {
      "suggestIssuer": {
       "id": "supportcases.wallets.paymentInstruments.suggestIssuer",
       "path": "wallets/paymentInstruments:suggestIssuer",
       "httpMethod": "GET",
       "description": "Fetches suggestions for payment(credit card, bank, direct carrier billing) issuers.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    }
   }
  },
  "youtube": {
   "methods": {
    "onetimepurchases": {
     "id": "supportcases.youtube.onetimepurchases",
     "path": "youtube/onetimepurchases",
     "httpMethod": "POST",
     "description": "Gets a list of one time purchases.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    },
    "summary": {
     "id": "supportcases.youtube.summary",
     "path": "youtube/summary",
     "httpMethod": "POST",
     "description": "Get Customer Summary Information for entitlements and refund history.",
     "scopes": [
      "https://www.googleapis.com/auth/cases.readonly"
     ]
    }
   },
   "resources": {
    "components": {
     "methods": {
      "cancel": {
       "id": "supportcases.youtube.components.cancel",
       "path": "youtube/components:cancel",
       "httpMethod": "POST",
       "description": "Cancel/Downgrade component(s).",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      }
     }
    },
    "entitlements": {
     "methods": {
      "cancel": {
       "id": "supportcases.youtube.entitlements.cancel",
       "path": "youtube/entitlements:cancel",
       "httpMethod": "POST",
       "description": "Cancel entitlement.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    },
    "transactions": {
     "methods": {
      "listByEntitlements": {
       "id": "supportcases.youtube.transactions.listByEntitlements",
       "path": "youtube/transactions:listByEntitlements",
       "httpMethod": "POST",
       "description": "Get all transactions for entitlements.",
       "scopes": [
        "https://www.googleapis.com/auth/cases.readonly"
       ]
      },
      "refund": {
       "id": "supportcases.youtube.transactions.refund",
       "path": "youtube/transactions:refund",
       "httpMethod": "POST",
       "description": "Refund a batch of transactions.",
       "scopes": [
        "https://www.googleapis.com/auth/cases"
       ]
      }
     }
    }
   }
  }
 }
}
