{
 "kind": "discovery#restDescription",
 "etag": "\"oZqOFf-aKzMvpID-BwBAFJLe7Pk/kUYo1r4N7g46he-gAwtqbJMknnE\"",
 "discoveryVersion": "v1",
 "id": "analytics:v3",
 "name": "analytics",
 "version": "v3",
 "revision": "20121022",
 "title": "Google Analytics API",
 "description": "View and manage your Google Analytics data",
 "documentationLink": "https://developers.google.com/analytics/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/analytics/v3/",
 "basePath": "/analytics/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "analytics/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/analytics": {
     "description": "View and manage your Google Analytics data"
    },
    "https://www.googleapis.com/auth/analytics.readonly": {
     "description": "View your Google Analytics data"
    }
   }
  }
 },
 "resources": {
  "data": {
   "resources": {
    "ga": {
     "methods": {
      "get": {
       "id": "analytics.data.ga.get",
       "path": "data/ga",
       "httpMethod": "GET",
       "description": "Returns Analytics data for a profile.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "mcf": {
     "methods": {
      "get": {
       "id": "analytics.data.mcf.get",
       "path": "data/mcf",
       "httpMethod": "GET",
       "description": "Returns Analytics Multi-Channel Funnels data for a profile.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    }
   }
  },
  "management": {
   "resources": {
    "accounts": {
     "methods": {
      "list": {
       "id": "analytics.management.accounts.list",
       "path": "management/accounts",
       "httpMethod": "GET",
       "description": "Lists all accounts to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "customDataSources": {
     "methods": {
      "list": {
       "id": "analytics.management.customDataSources.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources",
       "httpMethod": "GET",
       "description": "List custom data sources to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "dailyUploads": {
     "methods": {
      "delete": {
       "id": "analytics.management.dailyUploads.delete",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads/{date}",
       "httpMethod": "DELETE",
       "description": "Delete uploaded data for the given date.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics"
       ]
      },
      "list": {
       "id": "analytics.management.dailyUploads.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads",
       "httpMethod": "GET",
       "description": "List daily uploads to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      },
      "upload": {
       "id": "analytics.management.dailyUploads.upload",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/dailyUploads/{date}/uploads",
       "httpMethod": "POST",
       "description": "Update/Overwrite data for a custom data source.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics"
       ],
       "supportsMediaUpload": true
      }
     }
    },
    "goals": {
     "methods": {
      "list": {
       "id": "analytics.management.goals.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
       "httpMethod": "GET",
       "description": "Lists goals to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "profiles": {
     "methods": {
      "list": {
       "id": "analytics.management.profiles.list",
       "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
       "httpMethod": "GET",
       "description": "Lists profiles to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "segments": {
     "methods": {
      "list": {
       "id": "analytics.management.segments.list",
       "path": "management/segments",
       "httpMethod": "GET",
       "description": "Lists advanced segments to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    },
    "webproperties": {
     "methods": {
      "list": {
       "id": "analytics.management.webproperties.list",
       "path": "management/accounts/{accountId}/webproperties",
       "httpMethod": "GET",
       "description": "Lists web properties to which the user has access.",
       "scopes": [
        "https://www.googleapis.com/auth/analytics",
        "https://www.googleapis.com/auth/analytics.readonly"
       ]
      }
     }
    }
   }
  }
 }
}
