// Copyright 2026 Google LLC.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated file. DO NOT EDIT.

// Package androiddeveloperidstatus provides access to the Android Developer ID Status API.
//
// For product documentation, see: https://developer.android.com/developer-verification/guides/check-registration-status
//
// # Library status
//
// These client libraries are officially supported by Google. However, this
// library is considered complete and is in maintenance mode. This means
// that we will address critical bugs and security issues but will not add
// any new features.
//
// When possible, we recommend using our newer
// [Cloud Client Libraries for Go](https://pkg.go.dev/cloud.google.com/go)
// that are still actively being worked and iterated on.
//
// # Creating a client
//
// Usage example:
//
//	import "google.golang.org/api/androiddeveloperidstatus/v1"
//	...
//	ctx := context.Background()
//	androiddeveloperidstatusService, err := androiddeveloperidstatus.NewService(ctx)
//
// In this example, Google Application Default Credentials are used for
// authentication. For information on how to create and obtain Application
// Default Credentials, see https://developers.google.com/identity/protocols/application-default-credentials.
//
// # Other authentication options
//
// To use an API key for authentication (note: some APIs do not support API
// keys), use [google.golang.org/api/option.WithAPIKey]:
//
//	androiddeveloperidstatusService, err := androiddeveloperidstatus.NewService(ctx, option.WithAPIKey("AIza..."))
//
// To use an OAuth token (e.g., a user token obtained via a three-legged OAuth
// flow, use [google.golang.org/api/option.WithTokenSource]:
//
//	config := &oauth2.Config{...}
//	// ...
//	token, err := config.Exchange(ctx, ...)
//	androiddeveloperidstatusService, err := androiddeveloperidstatus.NewService(ctx, option.WithTokenSource(config.TokenSource(ctx, token)))
//
// See [google.golang.org/api/option.ClientOption] for details on options.
package androiddeveloperidstatus // import "google.golang.org/api/androiddeveloperidstatus/v1"

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/googleapis/gax-go/v2/internallog"
	googleapi "google.golang.org/api/googleapi"
	internal "google.golang.org/api/internal"
	gensupport "google.golang.org/api/internal/gensupport"
	option "google.golang.org/api/option"
	internaloption "google.golang.org/api/option/internaloption"
	htransport "google.golang.org/api/transport/http"
)

// Always reference these packages, just in case the auto-generated code
// below doesn't.
var _ = bytes.NewBuffer
var _ = strconv.Itoa
var _ = fmt.Sprintf
var _ = json.NewDecoder
var _ = io.Copy
var _ = url.Parse
var _ = gensupport.MarshalJSON
var _ = googleapi.Version
var _ = errors.New
var _ = strings.Replace
var _ = context.Canceled
var _ = internaloption.WithDefaultEndpoint
var _ = internal.Version
var _ = internallog.New

const apiId = "androiddeveloperidstatus:v1"
const apiName = "androiddeveloperidstatus"
const apiVersion = "v1"
const basePath = "https://androiddeveloperidstatus.googleapis.com/"
const basePathTemplate = "https://androiddeveloperidstatus.UNIVERSE_DOMAIN/"
const mtlsBasePath = "https://androiddeveloperidstatus.mtls.googleapis.com/"

// NewService creates a new Service.
func NewService(ctx context.Context, opts ...option.ClientOption) (*Service, error) {
	opts = append(opts, internaloption.WithDefaultEndpoint(basePath))
	opts = append(opts, internaloption.WithDefaultEndpointTemplate(basePathTemplate))
	opts = append(opts, internaloption.WithDefaultMTLSEndpoint(mtlsBasePath))
	opts = append(opts, internaloption.EnableNewAuthLibrary())
	client, endpoint, err := htransport.NewClient(ctx, opts...)
	if err != nil {
		return nil, err
	}
	s := &Service{client: client, BasePath: basePath, logger: internaloption.GetLogger(opts)}
	s.Packages = NewPackagesService(s)
	if endpoint != "" {
		s.BasePath = endpoint
	}
	return s, nil
}

// New creates a new Service. It uses the provided http.Client for requests.
//
// Deprecated: please use NewService instead.
// To provide a custom HTTP client, use option.WithHTTPClient.
// If you are using google.golang.org/api/googleapis/transport.APIKey, use option.WithAPIKey with NewService instead.
func New(client *http.Client) (*Service, error) {
	if client == nil {
		return nil, errors.New("client is nil")
	}
	return NewService(context.TODO(), option.WithHTTPClient(client))
}

type Service struct {
	client    *http.Client
	logger    *slog.Logger
	BasePath  string // API endpoint base URL
	UserAgent string // optional additional User-Agent fragment

	Packages *PackagesService
}

func (s *Service) userAgent() string {
	if s.UserAgent == "" {
		return googleapi.UserAgent
	}
	return googleapi.UserAgent + " " + s.UserAgent
}

func NewPackagesService(s *Service) *PackagesService {
	rs := &PackagesService{s: s}
	rs.PackageRegistrationStatus = NewPackagesPackageRegistrationStatusService(s)
	return rs
}

type PackagesService struct {
	s *Service

	PackageRegistrationStatus *PackagesPackageRegistrationStatusService
}

func NewPackagesPackageRegistrationStatusService(s *Service) *PackagesPackageRegistrationStatusService {
	rs := &PackagesPackageRegistrationStatusService{s: s}
	return rs
}

type PackagesPackageRegistrationStatusService struct {
	s *Service
}

// PackageRegistrationStatus: Resource message PackageRegistrationStatus.
type PackageRegistrationStatus struct {
	// CertificateFingerprint: Output only. The SHA-256 fingerprint of the public
	// certificate represented as a 64-character lowercase hexadecimal string
	// without any colons or separators (e.g.,
	// `d6ac89ed1d0a805aad4b087d06d5f41645b814480b133fbc867ef7498d069e06`).
	CertificateFingerprint string `json:"certificateFingerprint,omitempty"`
	// Name: Identifier. The name of the package registration status resource.
	// Format: packages/{package}/packageRegistrationStatus `{package}` must follow
	// the specific format: The fully-qualified Android package name with dots
	// ('.') replaced by hyphens ('-') (e.g., `com-example-app` instead of
	// `com.example.app`).
	Name string `json:"name,omitempty"`
	// State: Output only. Registration state of the package, or pair.
	//
	// Possible values:
	//   "REGISTRATION_STATE_UNSPECIFIED" - Default value. This value is unused.
	//   "REGISTERED" - Package is registered with the given certificate
	// fingerprint.
	//   "NOT_REGISTERED" - Package is not registered with any public certificate.
	//   "REGISTERED_WITH_ANOTHER_CERTIFICATE_FINGERPRINT" - Package is registered
	// with another public certificate fingerprint.
	State string `json:"state,omitempty"`

	// ServerResponse contains the HTTP response code and headers from the server.
	googleapi.ServerResponse `json:"-"`
	// ForceSendFields is a list of field names (e.g. "CertificateFingerprint") to
	// unconditionally include in API requests. By default, fields with empty or
	// default values are omitted from API requests. See
	// https://pkg.go.dev/google.golang.org/api#hdr-ForceSendFields for more
	// details.
	ForceSendFields []string `json:"-"`
	// NullFields is a list of field names (e.g. "CertificateFingerprint") to
	// include in API requests with the JSON null value. By default, fields with
	// empty values are omitted from API requests. See
	// https://pkg.go.dev/google.golang.org/api#hdr-NullFields for more details.
	NullFields []string `json:"-"`
}

func (s PackageRegistrationStatus) MarshalJSON() ([]byte, error) {
	type NoMethod PackageRegistrationStatus
	return gensupport.MarshalJSON(NoMethod(s), s.ForceSendFields, s.NullFields)
}

type PackagesPackageRegistrationStatusCheckCall struct {
	s            *Service
	name         string
	urlParams_   gensupport.URLParams
	ifNoneMatch_ string
	ctx_         context.Context
	header_      http.Header
}

// Check: Retrieves the Android Developer ID registration status for a given
// package.
//
//   - name: The name of the package registration status resource. Format:
//     packages/{package}/packageRegistrationStatus `{package}` must follow the
//     specific format: The fully-qualified Android package name with dots ('.')
//     replaced by hyphens ('-') (e.g., `com-example-app` instead of
//     `com.example.app`).
func (r *PackagesPackageRegistrationStatusService) Check(name string) *PackagesPackageRegistrationStatusCheckCall {
	c := &PackagesPackageRegistrationStatusCheckCall{s: r.s, urlParams_: make(gensupport.URLParams)}
	c.name = name
	return c
}

// CertificateFingerprint sets the optional parameter "certificateFingerprint":
// The SHA-256 fingerprint of the public certificate represented as a
// 64-character lowercase hexadecimal string without any colons or separators
// (e.g., `d6ac89ed1d0a805aad4b087d06d5f41645b814480b133fbc867ef7498d069e06`).
func (c *PackagesPackageRegistrationStatusCheckCall) CertificateFingerprint(certificateFingerprint string) *PackagesPackageRegistrationStatusCheckCall {
	c.urlParams_.Set("certificateFingerprint", certificateFingerprint)
	return c
}

// Fields allows partial responses to be retrieved. See
// https://developers.google.com/gdata/docs/2.0/basics#PartialResponse for more
// details.
func (c *PackagesPackageRegistrationStatusCheckCall) Fields(s ...googleapi.Field) *PackagesPackageRegistrationStatusCheckCall {
	c.urlParams_.Set("fields", googleapi.CombineFields(s))
	return c
}

// IfNoneMatch sets an optional parameter which makes the operation fail if the
// object's ETag matches the given value. This is useful for getting updates
// only after the object has changed since the last request.
func (c *PackagesPackageRegistrationStatusCheckCall) IfNoneMatch(entityTag string) *PackagesPackageRegistrationStatusCheckCall {
	c.ifNoneMatch_ = entityTag
	return c
}

// Context sets the context to be used in this call's Do method.
func (c *PackagesPackageRegistrationStatusCheckCall) Context(ctx context.Context) *PackagesPackageRegistrationStatusCheckCall {
	c.ctx_ = ctx
	return c
}

// Header returns a http.Header that can be modified by the caller to add
// headers to the request.
func (c *PackagesPackageRegistrationStatusCheckCall) Header() http.Header {
	if c.header_ == nil {
		c.header_ = make(http.Header)
	}
	return c.header_
}

func (c *PackagesPackageRegistrationStatusCheckCall) doRequest(alt string) (*http.Response, error) {
	reqHeaders := gensupport.SetHeaders(c.s.userAgent(), "", c.header_)
	if c.ifNoneMatch_ != "" {
		reqHeaders.Set("If-None-Match", c.ifNoneMatch_)
	}
	c.urlParams_.Set("alt", alt)
	c.urlParams_.Set("prettyPrint", "false")
	urls := googleapi.ResolveRelative(c.s.BasePath, "v1/{+name}:check")
	urls += "?" + c.urlParams_.Encode()
	req, err := http.NewRequest("GET", urls, nil)
	if err != nil {
		return nil, err
	}
	req.Header = reqHeaders
	googleapi.Expand(req.URL, map[string]string{
		"name": c.name,
	})
	c.s.logger.DebugContext(c.ctx_, "api request", "serviceName", apiName, "rpcName", "androiddeveloperidstatus.packages.packageRegistrationStatus.check", "request", internallog.HTTPRequest(req, nil))
	return gensupport.SendRequest(c.ctx_, c.s.client, req)
}

// Do executes the "androiddeveloperidstatus.packages.packageRegistrationStatus.check" call.
// Any non-2xx status code is an error. Response headers are in either
// *PackageRegistrationStatus.ServerResponse.Header or (if a response was
// returned at all) in error.(*googleapi.Error).Header. Use
// googleapi.IsNotModified to check whether the returned error was because
// http.StatusNotModified was returned.
func (c *PackagesPackageRegistrationStatusCheckCall) Do(opts ...googleapi.CallOption) (*PackageRegistrationStatus, error) {
	gensupport.SetOptions(c.urlParams_, opts...)
	res, err := c.doRequest("json")
	if res != nil && res.StatusCode == http.StatusNotModified {
		if res.Body != nil {
			res.Body.Close()
		}
		return nil, gensupport.WrapError(&googleapi.Error{
			Code:   res.StatusCode,
			Header: res.Header,
		})
	}
	if err != nil {
		return nil, err
	}
	defer googleapi.CloseBody(res)
	if err := googleapi.CheckResponse(res); err != nil {
		return nil, gensupport.WrapError(err)
	}
	ret := &PackageRegistrationStatus{
		ServerResponse: googleapi.ServerResponse{
			Header:         res.Header,
			HTTPStatusCode: res.StatusCode,
		},
	}
	target := &ret
	b, err := gensupport.DecodeResponseBytes(target, res)
	if err != nil {
		return nil, err
	}
	c.s.logger.DebugContext(c.ctx_, "api response", "serviceName", apiName, "rpcName", "androiddeveloperidstatus.packages.packageRegistrationStatus.check", "response", internallog.HTTPResponse(res, b))
	return ret, nil
}
