{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/MuNbTn-U7uo4q5kIHWudYUMbnVc\"",
 "discoveryVersion": "v1",
 "id": "replicapoolupdater:v1beta1",
 "name": "replicapoolupdater",
 "version": "v1beta1",
 "revision": "20150114",
 "title": "Google Compute Engine Instance Group Updater API",
 "description": "The Google Compute Engine Instance Group Updater API provides services for updating groups of Compute Engine Instances.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service",
 "labels": [
  "limited_availability"
 ],
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/replicapoolupdater/v1beta1/projects/",
 "basePath": "/replicapoolupdater/v1beta1/projects/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "replicapoolupdater/v1beta1/projects/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/replicapool": {
     "description": "View and manage replica pools"
    },
    "https://www.googleapis.com/auth/replicapool.readonly": {
     "description": "View replica pools"
    }
   }
  }
 },
 "resources": {
  "rollingUpdates": {
   "methods": {
    "cancel": {
     "id": "replicapoolupdater.rollingUpdates.cancel",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel",
     "httpMethod": "POST",
     "description": "Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "get": {
     "id": "replicapoolupdater.rollingUpdates.get",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}",
     "httpMethod": "GET",
     "description": "Returns information about an update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "insert": {
     "id": "replicapoolupdater.rollingUpdates.insert",
     "path": "{project}/zones/{zone}/rollingUpdates",
     "httpMethod": "POST",
     "description": "Inserts and starts a new update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "list": {
     "id": "replicapoolupdater.rollingUpdates.list",
     "path": "{project}/zones/{zone}/rollingUpdates",
     "httpMethod": "GET",
     "description": "Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "listInstanceUpdates": {
     "id": "replicapoolupdater.rollingUpdates.listInstanceUpdates",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates",
     "httpMethod": "GET",
     "description": "Lists the current status for each instance within a given update.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool",
      "https://www.googleapis.com/auth/replicapool.readonly"
     ]
    },
    "pause": {
     "id": "replicapoolupdater.rollingUpdates.pause",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause",
     "httpMethod": "POST",
     "description": "Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "resume": {
     "id": "replicapoolupdater.rollingUpdates.resume",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume",
     "httpMethod": "POST",
     "description": "Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    },
    "rollback": {
     "id": "replicapoolupdater.rollingUpdates.rollback",
     "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback",
     "httpMethod": "POST",
     "description": "Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.",
     "scopes": [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/replicapool"
     ]
    }
   }
  }
 }
}
