{
 "kind": "discovery#restDescription",
 "etag": "\"oZqOFf-aKzMvpID-BwBAFJLe7Pk/TOdPgdcxJiSF2xkjK1KcVgVS110\"",
 "discoveryVersion": "v1",
 "id": "youtube:v3",
 "name": "youtube",
 "canonicalName": "YouTube",
 "version": "v3",
 "revision": "20121022",
 "title": "YouTube API",
 "description": "Programmatic access to YouTube features.",
 "documentationLink": "https://developers.google.com/youtube",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/youtube/v3/",
 "basePath": "/youtube/v3/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "youtube/v3/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/youtube": {
     "description": "Manage your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.readonly": {
     "description": "View your YouTube account"
    },
    "https://www.googleapis.com/auth/youtube.upload": {
     "description": "Manage your YouTube videos"
    },
    "https://www.googleapis.com/auth/youtubepartner": {
     "description": "View and manage your assets and associated content on YouTube"
    }
   }
  }
 },
 "resources": {
  "activities": {
   "methods": {
    "insert": {
     "id": "youtube.activities.insert",
     "path": "activities",
     "httpMethod": "POST",
     "description": "Post a channel bulletin.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube"
     ]
    },
    "list": {
     "id": "youtube.activities.list",
     "path": "activities",
     "httpMethod": "GET",
     "description": "Browse the YouTube channel activity collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly"
     ]
    }
   }
  },
  "channels": {
   "methods": {
    "list": {
     "id": "youtube.channels.list",
     "path": "channels",
     "httpMethod": "GET",
     "description": "Browse the YouTube channel collection. Either the 'id' or 'mine' parameter must be set.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "guideCategories": {
   "methods": {
    "list": {
     "id": "youtube.guideCategories.list",
     "path": "guideCategories",
     "httpMethod": "GET",
     "description": "Browse the YouTube guide category collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "playlistItems": {
   "methods": {
    "delete": {
     "id": "youtube.playlistItems.delete",
     "path": "playlistItems",
     "httpMethod": "DELETE",
     "description": "Deletes playlist items by IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.playlistItems.insert",
     "path": "playlistItems",
     "httpMethod": "POST",
     "description": "Insert a resource into a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.playlistItems.list",
     "path": "playlistItems",
     "httpMethod": "GET",
     "description": "Browse the YouTube playlist collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.playlistItems.update",
     "path": "playlistItems",
     "httpMethod": "PUT",
     "description": "Update a playlist item.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "playlists": {
   "methods": {
    "delete": {
     "id": "youtube.playlists.delete",
     "path": "playlists",
     "httpMethod": "DELETE",
     "description": "Deletes playlists by IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.playlists.insert",
     "path": "playlists",
     "httpMethod": "POST",
     "description": "Create a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.playlists.list",
     "path": "playlists",
     "httpMethod": "GET",
     "description": "Browse the YouTube playlist collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.playlists.update",
     "path": "playlists",
     "httpMethod": "PUT",
     "description": "Update a playlist.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "search": {
   "methods": {
    "list": {
     "id": "youtube.search.list",
     "path": "search",
     "httpMethod": "GET",
     "description": "Universal search for youtube.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "subscriptions": {
   "methods": {
    "delete": {
     "id": "youtube.subscriptions.delete",
     "path": "subscriptions",
     "httpMethod": "DELETE",
     "description": "Deletes subscriptions by IDs.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.subscriptions.insert",
     "path": "subscriptions",
     "httpMethod": "POST",
     "description": "Insert a subscription.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "list": {
     "id": "youtube.subscriptions.list",
     "path": "subscriptions",
     "httpMethod": "GET",
     "description": "Browses the subscriptions collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "videoCategories": {
   "methods": {
    "list": {
     "id": "youtube.videoCategories.list",
     "path": "videoCategories",
     "httpMethod": "GET",
     "description": "Browse list of video categories.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  },
  "videos": {
   "methods": {
    "delete": {
     "id": "youtube.videos.delete",
     "path": "videos",
     "httpMethod": "DELETE",
     "description": "Delete a YouTube video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "insert": {
     "id": "youtube.videos.insert",
     "path": "videos",
     "httpMethod": "POST",
     "description": "Upload a video to YouTube.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.upload"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "youtube.videos.list",
     "path": "videos",
     "httpMethod": "GET",
     "description": "Browse the YouTube video collection.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtube.readonly",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    },
    "update": {
     "id": "youtube.videos.update",
     "path": "videos",
     "httpMethod": "PUT",
     "description": "Update a video.",
     "scopes": [
      "https://www.googleapis.com/auth/youtube",
      "https://www.googleapis.com/auth/youtubepartner"
     ]
    }
   }
  }
 }
}
