include $(GOROOT)/src/Make.inc
PREREQ=$(QUOTED_GOROOT)/pkg/$(GOOS)_$(GOARCH)/google-api-go-client.googlecode.com/hg/google-api.a
TARG=google-api-go-client.googlecode.com/hg/calendar/v3
GOFILES=calendar-gen.go
include $(GOROOT)/src/Make.pkg
