{
 "kind": "discovery#restDescription",
 "discoveryVersion": "v1",
 "id": "drive:v2",
 "name": "drive",
 "version": "v2",
 "revision": "20120501",
 "title": "Drive API",
 "description": "The API to interact with Drive.",
 "documentationLink": "https://developers.google.com/drive/",
 "protocol": "rest",
 "baseUrl": "https://www.googleapis.com/drive/v2/",
 "basePath": "/drive/v2/",
 "rootUrl": "https://www.googleapis.com/",
 "servicePath": "drive/v2/",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/drive": {
     "description": "View and manage the files and documents in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.apps.readonly": {
     "description": "New service: https://www.googleapis.com/auth/drive.apps.readonly"
    },
    "https://www.googleapis.com/auth/drive.file": {
     "description": "View and manage Google Drive files that you have opened or created with this app"
    },
    "https://www.googleapis.com/auth/drive.metadata.readonly": {
     "description": "View metadata for files and documents in your Google Drive"
    },
    "https://www.googleapis.com/auth/drive.readonly": {
     "description": "View the files and documents in your Google Drive"
    }
   }
  }
 },
 "resources": {
  "about": {
   "methods": {
    "get": {
     "id": "drive.about.get",
     "path": "about",
     "httpMethod": "GET",
     "description": "Gets the information about the current user along with Drive API settings",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "apps": {
   "methods": {
    "list": {
     "id": "drive.apps.list",
     "path": "apps",
     "httpMethod": "GET",
     "description": "Lists a user's apps.",
     "scopes": [
      "https://www.googleapis.com/auth/drive.apps.readonly"
     ]
    }
   }
  },
  "changes": {
   "methods": {
    "get": {
     "id": "drive.changes.get",
     "path": "changes/{changeId}",
     "httpMethod": "GET",
     "description": "Gets a specific change.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.changes.list",
     "path": "changes",
     "httpMethod": "GET",
     "description": "Lists the changes for a user.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "children": {
   "methods": {
    "delete": {
     "id": "drive.children.delete",
     "path": "files/{folderId}/children/{childId}",
     "httpMethod": "DELETE",
     "description": "Removes a child from a folder.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.children.get",
     "path": "files/{folderId}/children/{childId}",
     "httpMethod": "GET",
     "description": "Gets a specific child reference.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "insert": {
     "id": "drive.children.insert",
     "path": "files/{folderId}/children",
     "httpMethod": "POST",
     "description": "Inserts a file into a folder.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "list": {
     "id": "drive.children.list",
     "path": "files/{folderId}/children",
     "httpMethod": "GET",
     "description": "Lists a folder's children.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "files": {
   "methods": {
    "copy": {
     "id": "drive.files.copy",
     "path": "files/{fileId}/copy",
     "httpMethod": "POST",
     "description": "Creates a copy of the specified file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "delete": {
     "id": "drive.files.delete",
     "path": "files/{fileId}",
     "httpMethod": "DELETE",
     "description": "Permanently deletes a file by ID. Skips the trash.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.files.get",
     "path": "files/{fileId}",
     "httpMethod": "GET",
     "description": "Gets a file's metadata by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "insert": {
     "id": "drive.files.insert",
     "path": "files",
     "httpMethod": "POST",
     "description": "Insert a new file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ],
     "supportsMediaUpload": true
    },
    "list": {
     "id": "drive.files.list",
     "path": "files",
     "httpMethod": "GET",
     "description": "Lists the user's files.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "patch": {
     "id": "drive.files.patch",
     "path": "files/{fileId}",
     "httpMethod": "PATCH",
     "description": "Updates file metadata and/or content. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "touch": {
     "id": "drive.files.touch",
     "path": "files/{fileId}/touch",
     "httpMethod": "POST",
     "description": "Set the file's updated time to the current server time.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "trash": {
     "id": "drive.files.trash",
     "path": "files/{fileId}/trash",
     "httpMethod": "POST",
     "description": "Moves a file to the trash.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "untrash": {
     "id": "drive.files.untrash",
     "path": "files/{fileId}/untrash",
     "httpMethod": "POST",
     "description": "Restores a file from the trash.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "update": {
     "id": "drive.files.update",
     "path": "files/{fileId}",
     "httpMethod": "PUT",
     "description": "Updates file metadata and/or content",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ],
     "supportsMediaUpload": true
    }
   }
  },
  "parents": {
   "methods": {
    "delete": {
     "id": "drive.parents.delete",
     "path": "files/{fileId}/parents/{parentId}",
     "httpMethod": "DELETE",
     "description": "Removes a parent from a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.parents.get",
     "path": "files/{fileId}/parents/{parentId}",
     "httpMethod": "GET",
     "description": "Gets a specific parent reference.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "insert": {
     "id": "drive.parents.insert",
     "path": "files/{fileId}/parents",
     "httpMethod": "POST",
     "description": "Adds a parent folder for a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "list": {
     "id": "drive.parents.list",
     "path": "files/{fileId}/parents",
     "httpMethod": "GET",
     "description": "Lists a file's parents.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    }
   }
  },
  "permissions": {
   "methods": {
    "delete": {
     "id": "drive.permissions.delete",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "DELETE",
     "description": "Deletes a permission from a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.permissions.get",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "GET",
     "description": "Gets a permission by ID.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "insert": {
     "id": "drive.permissions.insert",
     "path": "files/{fileId}/permissions",
     "httpMethod": "POST",
     "description": "Inserts a permission for a file.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "list": {
     "id": "drive.permissions.list",
     "path": "files/{fileId}/permissions",
     "httpMethod": "GET",
     "description": "Lists a file's permissions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "patch": {
     "id": "drive.permissions.patch",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "PATCH",
     "description": "Updates a permission. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "update": {
     "id": "drive.permissions.update",
     "path": "files/{fileId}/permissions/{permissionId}",
     "httpMethod": "PUT",
     "description": "Updates a permission.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  },
  "revisions": {
   "methods": {
    "delete": {
     "id": "drive.revisions.delete",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "DELETE",
     "description": "Removes a revision.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "get": {
     "id": "drive.revisions.get",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "GET",
     "description": "Gets a specific revision.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "list": {
     "id": "drive.revisions.list",
     "path": "files/{fileId}/revisions",
     "httpMethod": "GET",
     "description": "Lists a file's revisions.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "https://www.googleapis.com/auth/drive.readonly"
     ]
    },
    "patch": {
     "id": "drive.revisions.patch",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "PATCH",
     "description": "Updates a revision. This method supports patch semantics.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    },
    "update": {
     "id": "drive.revisions.update",
     "path": "files/{fileId}/revisions/{revisionId}",
     "httpMethod": "PUT",
     "description": "Updates a revision.",
     "scopes": [
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/drive.file"
     ]
    }
   }
  }
 }
}
